actions:
  - type: takeoff_from_UGV
    ins_id: take_off_1

  - type: move_to_location
    ins_id: move_1
    location:
      lat: 41.870111
      lon: -87.650272

  - type: move_to_location
    ins_id: move_2
    location:
      lat: 41.870132
      lon: -87.650127

  - type: move_to_location
    ins_id: move_3
    location:
      lat: 41.870065
      lon: -87.649971

  - type: move_to_location
    ins_id: move_4
    location:
      lat: 41.870040
      lon: -87.650356

  - type: land_on_UGV
    ins_id: land_1

